version: "3"
services:
  web:
    build:
      context: ./docker/web
      args:
        - TZ=${TZ}
    ports:
      - 5000:80
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/apache2
      - ./logs:/var/log/php
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}

  db:
    build:
      context: ./docker/db
    ports: 
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
